### ISSUE TITLE
Parameter name

### ISSUE THREAD

**Issue by Valdecy** [Diyago/Tabular-data-generation#1]
In models.py 
class Generator(Module):
    def __init__(self, embedding_dim, gen_dims, data_dim):

should not be

class Generator(Module):
    def __init__(self, embedding_dim, gen_dim, data_dim):

gen_dims is equal gen_dim?

**Comment by Diyago** [comment]
It's just parameters naming, take a look at its actual initialization:
```python
        self.generator = Generator(
            self.embedding_dim + self.cond_generator.n_opt,
            self.gen_dim,
            data_dim
        ).to(self.device)
```
But you right it should be as you suggested with ```gen_dim```
