### ISSUE TITLE
support Python>=3.7

### ISSUE THREAD

**Issue by yair4Data** [Diyago/Tabular-data-generation#13]
1.0.3 release requires python version 3.6.10
any newer version doesn't let install the wheel.
plus - there is no tar.gz file in pip installation so can't install without the wheel file.

**Comment by Diyago** [comment]
@yair4Data how do you install the library? Console logs will be great

ps didnt fixed yet but recently released 1.0.4

**Comment by yair4Data** [comment]
@Diyago - i can't copy the logs because of restricted machine issue.
but i simply downloaded the wheel and did :
pip install tabgan-1.0.3-py2.py3-none-any.whl
and got : 
ERROR: Package 'tabgan' requires a different Python : 3.6.10 not in '>=3.7'
so it seems that tabgan support only python >=3.7
is that the case ?

**Comment by Diyago** [comment]
I can't reproduce your problem:

I tried direct install "pip install tabgan" - works well

Then by downloading whl file:
```
⋊> pip install tabgan-1.0.4-py2.py3-none-any.whl              15:18:20
Processing ./tabgan-1.0.4-py2.py3-none-any.whl
....

Installing collected packages: tabgan
  Attempting uninstall: tabgan
    Found existing installation: tabgan 1.0.3
    Uninstalling tabgan-1.0.3:
      Successfully uninstalled tabgan-1.0.3
Successfully installed tabgan-1.0.4
```


PS I have python 3.8.3:
```
⋊> ~ python                                                               15:17:11
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version
'3.8.3 (default, Jul  2 2020, 11:26:31) \n[Clang 10.0.0 ]'
```

**Comment by Diyago** [comment]
Any chance you reproduce it on colab or Kaggle notebooks?

**Comment by yair4Data** [comment]
so it obvious that the issue is the dependency of python>=3.7 .
since i have 3.6.10 version - it fails.
any reason not to support python >=3.6 ?

**Comment by Diyago** [comment]
@yair4Data I believe there is no problem. I will check it out and release new version with support 3.6 today

**Comment by yair4Data** [comment]
thanks!

**Comment by Diyago** [comment]
@yair4Data  Please check it - https://pypi.org/project/tabgan/1.0.5/

<img width="278" alt="image" src="https://user-images.githubusercontent.com/8073766/111995415-f2e5d280-8b29-11eb-9ceb-5b8f523bfd6d.png">

**Comment by yair4Data** [comment]
success on installing it, but when trying to run - had issues with torch version.
the requirement is for torch==1.8.0
i need lower version...since i get GTLIB issues on the 1.8.0 version....

**Comment by Diyago** [comment]
I believe its installed by pip latest version. Try to install by your self. In requerments.txt torch==1.6.0

**Comment by yair4Data** [comment]
apparently it comes from:
from _ctgan.synthesizer import _CTGANSynthesizer
version `GLIBC_2.14 not found

**Comment by Diyago** [comment]
Im not sure, that I may help you with such problems:
Try to Google it
https://superuser.com/questions/537683/how-to-fix-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-14-not-found
