### ISSUE TITLE
ValueError: Input train dataframe already have 0 column, consider removing it

### ISSUE THREAD

**Issue by lablebi96** [Diyago/Tabular-data-generation#15]
**Describe the bug**
Traceback (most recent call last):
  File "c:\Users\yrouis2\Desktop\KCA-codes\GANs\TestGANs.py", line 30, in <module>
    new_train3, new_target3 = GANGenerator(gen_x_times=1.1, cat_cols=None, bot_filter_quantile=0.001,
  File "C:\Users\yrouis2\Desktop\KCA-codes\GANs\gans\lib\site-packages\tabgan\abc_sampler.py", line 41, in generate_data_pipe
    new_train, new_target, test_df = generator.preprocess_data(train_df.copy(), target.copy(), test_df)
  File "C:\Users\yrouis2\Desktop\KCA-codes\GANs\gans\lib\site-packages\tabgan\sampler.py", line 90, in preprocess_data
    raise ValueError(
ValueError: Input train dataframe already have 0 column, consider removing it

Hello, first of all thank you for sharing the code ! 
I have an issue,  I passed my dataset to the generator but got this error everytime, does that mean that my dataset contains a column of zeros in all rows ? if yes what's the problem of not considering it

**Comment by Diyago** [comment]
Hi!

This errors comes from this function call:
``` python
def preprocess_data(self, train_df, target, test_df, ) -> Tuple[pd.DataFrame, pd.DataFrame]:
        if isinstance(train_df, pd.DataFrame) is False or isinstance(target, pd.DataFrame) is False \
                or isinstance(test_df, pd.DataFrame) is False:
            raise ValueError("Input dataframes aren't pandas dataframes: train is {}; target is ; test is {}".
                             format(type(train_df), type(target), type(test_df)))
        self.TEMP_TARGET = target.columns[0]
        if self.TEMP_TARGET in train_df.columns:
            raise ValueError(
                "Input train dataframe already have {} column, consider removing it".format(self.TEMP_TARGET))

```

So you actually have same named column in train dataset as you have in your target column. 
Rename target column. And reopen if still error persists.

**Comment by lablebi96** [comment]
I renamed the target column from 0 to 'target' with : target = target.rename(columns={0 : "target"}) and it worked. 
Thank you for helping !
