### ISSUE TITLE
Generating samples for only One class among two available

### ISSUE THREAD

**Issue by lablebi96** [Diyago/Tabular-data-generation#16]
Hello,

After giving my data that contains two classes (equilibrated size 50% of data each class) as input to the GANGenerator, the output generated data was : 
5.665401393688743e-05 for one class and 0.9999433459860632 for the other one. 

Do you may know the origins of this issue ?  

Best regards

**Comment by Diyago** [comment]
Could you please provide stats for input dataframes (train with target 0 and target = 1 and  test) 

df.describe() - will be enough 


Also providing input params will be great

**Comment by lablebi96** [comment]
>>> train.describe()
                 0             1             2   ...            10            11            12        
count  65711.000000  65711.000000  65711.000000  ...  65711.000000  65711.000000  65711.000000        
mean     135.567264     96.909816    232.477079  ...      0.311261      0.327115      0.181479        
std      171.279123    364.581398    352.569126  ...      0.320950      0.334021      0.210505        
min        2.956629  -3994.149208  -3810.783863  ...      0.000000      0.000000      0.000000        
25%       88.186860      0.000000    102.165580  ...      0.000000      0.012987      0.000000        
50%      105.319738     67.817450    171.265125  ...      0.004049      0.047619      0.026144        
75%      129.930615    139.993191    255.311251  ...      0.612245      0.646259      0.351852        
max     4101.103306   1913.887978   1999.898911  ...      1.000000      1.000000      1.000000        

[8 rows x 13 columns]
>>> test.describe()  
                0            1            2   ...           10           11           12
count  8022.000000  8022.000000  8022.000000  ...  8022.000000  8022.000000  8022.000000
mean    124.719428   210.234072   334.953500  ...     0.117666     0.312081     0.512029
std      93.247148   351.019262   362.286603  ...     0.151850     0.136116     0.162687
min       0.993013 -3431.263208 -3322.556257  ...     0.000000     0.000000     0.000000
25%      93.735814    56.848168   167.552471  ...     0.012048     0.250000     0.413793
50%     104.710460   118.676901   222.395062  ...     0.052632     0.348485     0.533981
75%     120.717764   237.457216   363.037884  ...     0.212121     0.416667     0.614286
max    1610.692024  1869.678259  1992.671490  ...     1.000000     1.000000     1.000000

[8 rows x 13 columns]
>>> target.describe() 
             target
count  65711.000000
mean       0.504573
std        0.499983
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000

Here are the train, test and target .describe() outputs

**Comment by Diyago** [comment]
If you look at the post-process function  you will see that it filters from train data, which out of test shapes:
```
def postprocess_data(self, train_df, target, test_df, ):
        if not self.is_post_process:
            return train_df, target
        self._validate_data(train_df, target, test_df)
        train_df[self.TEMP_TARGET] = target
        for num_col in train_df.columns:
            if (self.cat_cols is None or num_col not in self.cat_cols) \
                    and num_col != self.TEMP_TARGET:
                min_val = test_df[num_col].quantile(self.bot_filter_quantile)
                max_val = test_df[num_col].quantile(self.top_filter_quantile)

                filtered_df = train_df.loc[(train_df[num_col] >= min_val) & (train_df[num_col] <= max_val)]
                train_df = filtered_df

        if self.cat_cols is not None:
            for cat_col in self.cat_cols:
                filtered_df = train_df[train_df[cat_col].isin(test_df[cat_col].unique())]
                train_df = filtered_df
        gc.collect()
        return train_df.drop(self.TEMP_TARGET, axis=1).reset_index(drop=True), train_df[self.TEMP_TARGET].reset_index(
            drop=True)
```

And your provided data is highly skewed, for example for 12th column in train mean is 0.18 for test 0.51. More than 2 times differs. Sames with max values.

**Comment by Diyago** [comment]
You can disable postprocessing this way: is_post_process=False and disable adversarial filtering this way: use_adversarial = False

**Comment by Diyago** [comment]
By the way, you may try OriginalSampler which may give different results.  

@lablebi96 reopen if problem is still persist
