### ISSUE TITLE
not running on GPU 

### ISSUE THREAD

**Issue by colinpriest** [Diyago/Tabular-data-generation#17]
**Describe the bug**
The library isn't using GPU when cuda is available.

**To Reproduce**
Run the sample script. Check GPU usage - no GPU used.

**Expected behavior**
The library should recognise when cuda is available, and use GPU for the calculations.

**Screenshots**

**Desktop (please complete the following information):**
Problem occurs on Windows and Google Colab. May possibly occur on other platforms.

**Additional context**

**Comment by colinpriest** [comment]
Here's a script I have been using to test GPU usage, but can only see CPU usage.

import torch
print(torch.cuda.is_available())
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from tabgan.sampler import OriginalGenerator, GANGenerator
# read workers compensation data
X = pd.read_excel("https://datarobotfiles.s3-ap-southeast-1.amazonaws.com/20210502X_train3.xlsx")
y = pd.read_csv("https://datarobotfiles.s3-ap-southeast-1.amazonaws.com/20210502y_target.csv", low_memory=False)
## one hot encoding
X = pd.get_dummies(X)
# training, test, and target split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Finished setting up data!")
# generate data
new_train2, new_target2 = GANGenerator().generate_data_pipe(X_train, y_train, X_test, )
print("Finished generating data!")

**Comment by colinpriest** [comment]
By comparison, this Google colab script IS using GPU! There must be something in the extra parameters I added that is making GPU work.



import torch
import sys

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tabgan.sampler import OriginalGenerator, GANGenerator

print(torch.cuda.is_available())

X = pd.read_csv("https://datarobotfiles.s3-ap-southeast-1.amazonaws.com/XX.csv", low_memory=False)
# print(X.isna().any())
# one hot encoding
# X = pd.get_dummies(X)
print("Features loaded")

y = pd.read_csv("https://datarobotfiles.s3-ap-southeast-1.amazonaws.com/YY.csv", low_memory=False)
print("Target loaded")
# print(y.isna().any())

# training, test, and target split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Finished setting up data!")

# generate data
new_train2, new_target2 = GANGenerator(gen_x_times=1.1,
                                       cat_cols=["Gender", "MaritalStatus", "PartTimeFullTime",
                                                 "Word01", "Word02", "Word03", "Word04", "Word05",
                                                 "Word06", "Word07", "Word08", "Word09", "Word10"],
                                       adversaial_model_params={
                                           "metrics": "AUC", "max_depth": 3,
                                           "max_bin": 100, "n_estimators": 500,
                                           "learning_rate": 0.01, "random_state": 42,
                                       },
                                       epochs=1000).generate_data_pipe(X_train, y_train, X_test, )
# new_train2, new_target2 = OriginalGenerator().generate_data_pipe(X_train, y_train, X_test, )
print("Finished generating data!")

print(new_train2)

**Comment by colinpriest** [comment]
I'm getting more confused. I just managed to get GPU to run just using the default function call for GANGenerator and generate_data_pipeline.

But 
* for the first 3 minutes (approximately) it only uses CPU, then it suddenly starts using GPU.
* when I don't include any custom function parameters, it uses 25% of GPU, whereas  when I set custom parameters it uses 80% of GPU

**Comment by Diyago** [comment]
Hmm, sorry for the late answer.  I believe you see different GPU usage on different steps of the pipeline. For example, generate_daa_pipe looks this way:
``` python 
new_train, new_target, test_df = generator.preprocess_data(train_df, target, test_df)
        if only_adversarial and use_adversarial:
            return generator.adversarial_filtering(new_train, new_target, test_df)
        else:
            new_train, new_target = generator.generate_data(new_train, new_target, test_df)
            new_train, new_target = generator.postprocess_data(new_train, new_target, test_df)
            if use_adversarial:
                new_train, new_target = generator.adversarial_filtering(new_train, new_target, test_df)

```
So it preprocesses then applies then   GAN with should use GPU and then applies adversarial filtering, which pretty heavy step as well. In addition applying get dummies increase number of features which cause different training steps

**Comment by Diyago** [comment]
If training or generating process is too  slow, you might increase you input data
