### ISSUE TITLE
Sampler demo freezes at same point, multiple installs.  Windows 10

### ISSUE THREAD

**Issue by KHBreslauer** [Diyago/Tabular-data-generation#19]
I have tried several installs on two different machines.  

Most recent, Win10, virtual env with py 3.8.11 and only your requirements.txt modules installed, plus Jupyter...

Most recent attempt: 
created virtual environment with python 3.8
(gann) C:\Users\klaus>python -V
Python 3.8.11

ran a renamed requirements.txt file rqr0.txt - no torch 1.6
(gann) C:\Users\klaus>python -m pip install -r rqr0.txt
ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1, 1.8.0, 1.8.1, 1.9.0)
ERROR: No matching distribution found for torch==1.6.0

So ; installed torch 1.6
(gann) C:\Users\klaus>conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch
Executing transaction: done

installed required modules
(gann) C:\Users\klaus>python -m pip install -r rqr0.txt

installed tabgan
(gann) C:\Users\klaus>pip install tabgan

ON ALL MACHINES, ALL INSTALLS, the sampler freezes at the same point with no error message.

Fitting CTGAN transformers for each column: 100% 5/5 [00:00<00:00, 9.31it/s]
Training CTGAN, epochs:: 33%   167/500 [00:04<00:06, 51.27it/s]
Fitting CTGAN transformers for each column: 100%  5/5 [00:00<00:00,10.67it/s]
Training CTGAN, epochs:: 23%

I have tried python 3.9 installs on two different computers.
What further info can I provide to give clues as to what is happening?
Thanks.

**Comment by Diyago** [comment]
Hi! Thank you for reaching out!

1. pls provide, input dataframe shapes and if possible df.describe() 
2. Provide input training params
3. Please try to pass to pipeline small dataframe

**Comment by KHBreslauer** [comment]
Stock demo code, copied and pasted has run successfully.  Very careful set of installs.  First conda installs for everything except those mentioned (PYTORCH seems to be the issue) in requirements.txt.  Then pip install -r requirements.txt.   Attempts doing all installs with pip have failed so far.  Still possible, but first success with conda/pip sequence.  Program runs but desired synth data is huge 960k row x 120 columns, so slow going and slicing into smaller trial dataframes.  Will advise after adversarial validation attempt.
