### ISSUE TITLE
Kindly ask for help in Google Colab

### ISSUE THREAD

**Issue by la269342** [Diyago/Tabular-data-generation#23]
Dear Insaf Ashrapov,
Lead Data Scientist at Sberbank,

thank you for your fruitful ideas and codes regarding GAN for tabular data published at:
https://github.com/Diyago/GAN-for-tabular-data
 
Recently, we applied your example code from the section „How to use the library“ in Google Colab and it performed well on our data. However, last two weeks we obtained an error in Google Colab environment.
<img width="1063" alt="colab_error" 
<img width="1063" alt="colab_error" src="https://user-images.githubusercontent.com/95305399/144094145-d767b40e-b11c-431f-9bda-18f1e6c1260b.png">
src="https://user-images.githubusercontent.com/95305399/144093966-11dceba2-ed13-4fd7-a6a9-aab9d7aeb2b0.png">

After using your example code in Google Colab, the following error was obtained (in the figure in attachment)

I would be very glad for your help and look at this issue.

Sincerely
Lubomir, Slovakia

**Comment by Diyago** [comment]
Hmm, that interesting. The error reproduced on a collab with python 3.7.12 but work smoothly on my pc with 3.8.2, 3.8.5 and on Kaggle machine with python 3.7.10

https://www.kaggle.com/insaff/tabular-gan-demo/log
![image](https://user-images.githubusercontent.com/8073766/144314962-91132322-8a2c-4159-8b6a-c8c11d46b0f3.png)

**Comment by Diyago** [comment]
I will continue the investigation. As temporary workaround use Kaggle notebooks or different python

**Comment by la269342** [comment]
Dear Insaf Ashrapov, thank you very much for your kind help and recommendations. We will try it alternatively. However, if you will find the answer, we would very glad to hear about it. 
I wish you a nice week.
Lubomir

**Comment by Diyago** [comment]
Finally, I came to the solution. Colab already has installed sklearn so I have to manually install the right version:
```!pip install scikit_learn==0.23.2§```

**Comment by Diyago** [comment]
@la269342  Fixed in the new version. Install this way:

!pip install tabgan==1.1.2

In colab you have to reload runtime
