### ISSUE TITLE
Trying to run how to use library part

### ISSUE THREAD

**Issue by Dubbix** [Diyago/Tabular-data-generation#24]
**Describe the bug**
How to tutorial not working for me

**To Reproduce**
1. Install pip and copypaste the example code under how to
2. ![image](https://user-images.githubusercontent.com/35582089/145561807-27f35f9d-2ad2-481b-9f86-8ac79422b1be.png)

**Expected behavior**
Get error that I give to many positional arguments

**Screenshots**
![image](https://user-images.githubusercontent.com/35582089/145561658-034fee69-ce4e-4543-be05-a63f7e424c75.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Diyago** [comment]
Fixed in the new version. Install this way:

!pip install tabgan==1.1.2

In colab you have to reload runtime
