### ISSUE TITLE
Cannot install tabgan

### ISSUE THREAD

**Issue by sparshgarg23** [Diyago/Tabular-data-generation#25]
**Describe the bug**
I installed tabgan on colab using pip,but when I did import tabgan I ran into the following error
ContextualVersionConflict: (scikit-learn 1.0.1 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('scikit-learn==0.23.2'), {'tabgan'})
On windows 10 python 3.9,tabgan installation fails because sci-kit wheel not being built
**To Reproduce**
1. Go to  colab
2. execute !pip install tabgan
3. execute import tabgan

**Expected behavior**
import tabgan should run without producing any errors
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu] Windows 10;colab

**Additional context**

**Comment by Diyago** [comment]
To proceed ContextualVersionConflict you have to reload colab runtime
