### ISSUE TITLE
Hello, when I run "python ./Research/run_experiment.py", I see the error,please help me, thanks!

### ISSUE THREAD

**Issue by hhcNWPU** [Diyago/Tabular-data-generation#26]
PS E:\GAN-for-tabular-data-master\GAN-for-tabular-data-master> python ./Research/run_experiment.py
Traceback (most recent call last):
  File "./Research/run_experiment.py", line 10, in <module>
    from utils import save_exp_to_file, extend_gan_train, extend_from_original
  File "E:\GAN-for-tabular-data-master\GAN-for-tabular-data-master\Research\utils.py", line 8, in <module>
    from ctgan import _CTGANSynthesizer
ImportError: cannot import name '_CTGANSynthesizer' from 'ctgan' (E:\GAN-for-tabular-data-master\GAN-for-tabular-data-master\Research\ctgan\__init__.py)

**Comment by Diyago** [comment]
pls show `pip list` results
