### ISSUE TITLE
_CTGANSynthesizer

### ISSUE THREAD

**Issue by WYF-GAN** [Diyago/Tabular-data-generation#28]
Dear researchers,

When i run the run_experiment.py, importError: cannot import name '_CTGANSynthesizer' from 'ctgan'. I find that the '_CTGANSynthesizer' was not defined in the ctgan. Am i right or i miss something? Thank you very much!

Regards,
Yufei

My pip installment is as follows 
category-encoders  2.1.0    
certifi            2021.10.8
charset-normalizer 2.0.12
colorama           0.4.4
idna               3.3
joblib             1.1.0
lightgbm           2.3.1
numpy              1.18.1
threadpoolctl      3.1.0
torch              1.8.0  (this is the higher version)
torchvision        0.12.0
tqdm               4.61.1
typing_extensions  4.2.0
urllib3            1.26.9
wheel              0.37.1

**Comment by Diyago** [comment]
Hi!

_CTGANSynthesizer is private class, which basically you shouldnt be using. Try using to use sample code from README.MD

Or you try to download the whole project and try it on your own

Reopen is issue still persists
