### ISSUE TITLE
generated Cov is not that close

### ISSUE THREAD

**Issue by dirknbr** [Diyago/Tabular-data-generation#31]
This is maybe more of a discussion point, I have three variables which have a covariance C, and I want the generated data to have the same covariance. At the moment the generated C is not that close to the true C.  

```
n = 1000
cov = np.array([[3, 2, 1], [2, 3, 2], [1, 2, 3]]) / 3
print(cov)

X = np.random.multivariate_normal([1, 2, 3], cov, n)

train = np.arange(n // 2)
test = np.arange(n // 2, n)

# predict x0 from x1 and x2
reg = linear_model.LinearRegression()
reg.fit(X[train, 1:], X[train, 0])
pred1 = reg.predict(X[test, 1:])
print(np.mean(abs(X[test, 0] - pred1)))

train_df = pd.DataFrame(X[train, 1:], columns=['a', 'b'])
target = pd.DataFrame(X[train, 0], columns=['y'])
test_df = pd.DataFrame(X[test, 1:], columns=list(train_df))

gen_x, gen_y = GANGenerator(gen_x_times=1.1).generate_data_pipe(train_df, target, test_df)

print(len(gen_x))

X2 = np.zeros((gen_x.shape[0], 3))
X2[:, 0] = gen_y
X2[:, 1:] = gen_x

print(X2.mean(axis=0))
print(np.cov(X2.T))

pred2 = reg.predict(X2[:, 1:])

print(np.mean(abs(pred2 - X2[:, 0])))

[1.24107277 2.19440913 2.56302274]
[[ 1.32843079  0.18899326 -0.05254613]
 [ 0.18899326  1.25402907  0.16901545]
 [-0.05254613  0.16901545  1.26216313]]

```

**Comment by Diyago** [comment]
I didnt qet what you would like to achieve.  Why is cov so important?


First of all you may with GAN params:

```
gen_x, gen_y = GANGenerator(bot_filter_quantile=0.001, top_filter_quantile=0.999, is_post_process=True,
           adversarial_model_params={
               "metrics": "AUC", "max_depth": 2, "max_bin": 100, 
               "learning_rate": 0.02, "random_state": 42, "n_estimators": 500,
           }, pregeneration_frac=2, only_generated_data=False,
           gan_params = {"batch_size": 500, "patience": 50, "epochs" : 500,},
           gen_x_times=1.2).generate_data_pipe(train_df, target, test_df)
```

Secondly:
Your generated data with np.random.multivariate_normal doest have same cov as you passed:
**what you wanted**
[[1.         0.66666667 0.33333333]
 [0.66666667 1.         0.66666667]
 [0.33333333 0.66666667 1.        ]]
**you actually generated**
[[0.91722526 0.62890772 0.3325362 ]
 [0.62890772 1.04560479 0.74625155]
 [0.3325362  0.74625155 1.09697827]]
**generated from gan** - looks prery similar to me
[[ 1.22316084  0.06813614 -0.02172127]
 [ 0.06813614  1.29201178  0.22556574]
 [-0.02172127  0.22556574  1.25738251]]

**Comment by Diyago** [comment]
Sorry for the late answer, if you didnt get required answers, please reopen question
