### ISSUE TITLE
training CTGAN stops in the middle (around 24%)

### ISSUE THREAD

**Issue by seanko29** [Diyago/Tabular-data-generation#41]
**Describe the bug**

While traing CTGAN, it stops in a certain percentage of epoch (mostly 20~30%)
**To Reproduce**

**Expected behavior**

Hello! 
As you mentioned in my previous issue, I tried running your example code and it is kind of working to a certain extent.
tqdm stops in 24% (or somewhere close to that number) of training CTGAN (screenshot added). 
No other messages appear but the code is done running. Am I missing something here? 
 
Thank you in advanced!

**Screenshots**

![image](https://user-images.githubusercontent.com/72428646/178176773-3a22b5dc-edc3-4d49-94ee-ea8e467d82d3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu]

jupyter notebook on ubuntu/linux server
google colab 

**Additional context**

**Comment by Diyago** [comment]
Thats normal behavior. You have set  500 epochs for gan training but with 25 epochs for early stopping, so then it reaches its stop training

**Comment by seanko29** [comment]
Thank you for your help!
