### ISSUE TITLE
Difference between OriginalGenerator and GANGenerator

### ISSUE THREAD

**Issue by seanko29** [Diyago/Tabular-data-generation#42]
Hello, 

First of all, I apologize to ask questions too frequently. However, I am using your code well so much :). Thanks in advanced!

My question is that while I was reading your arxiv paper, I saw that you wrote two different tabular gans (TGAN and CTGAN).
Thus, is the original generator pertaining to TGAN and 
GANGenerator is the CTGAN?

I am writing down notes to myself so that I can understand better.

Thank you!!

**Comment by Diyago** [comment]
there is only CTGAN used in GANGenerator)

original generato - is just resampling from original data
