### ISSUE TITLE
Getting this error when trying to install load 

### ISSUE THREAD

**Issue by mahii6991** [Diyago/Tabular-data-generation#44]
**Describe the bug**
(scikit-learn 1.0.2 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('scikit-learn==0.23.2'), {'tabgan'})

**To Reproduce**
1. Go to "google colab or kaggle".
2. Click on from "tabgan.sampler import OriginalGenerator, GANGenerator" to load the libraries.
3. See error

**Expected behavior**
It should load with out error because the requirements are already installed via pip.

**Screenshots**
![image](https://user-images.githubusercontent.com/61599939/180619762-3606c37a-b6c1-437f-a018-4a01dec2a647.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu]

**Comment by Diyago** [comment]
please reload kernel after instaling

**Comment by mahii6991** [comment]
I have reloaded kernel multiple times , but still getting the same error.!
