### ISSUE TITLE
Dear Author, May I know the ctgan version for the installation? I am getting error.      from ctgan import _CTGANSynthesizer ImportError: cannot import name '_CTGANSynthesizer'

### ISSUE THREAD

**Issue by Mah-Zam** [Diyago/Tabular-data-generation#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu]

**Additional context**

**Comment by Mah-Zam** [comment]
I could comment the "extend_gan_train" and imported library to continue on this.

**Comment by Diyago** [comment]
Show version library versuin installed and  your full code to reproduce

**Comment by Ng-ms** [comment]
Hello 
 I am getting the same error, it was working fine after a few days I tried to rerun it, and start giving me this error, I am using openesuse, python 3.6, scikit-learn-0.24.2

**Comment by Diyago** [comment]
@Ng-ms @Mah-Zam  Try latest release - everything works fine on colab 

`!pip install tabgan==1.3.0
`
