### ISSUE TITLE
pip install scikit-learn version issue

### ISSUE THREAD

**Issue by orkunaran** [Diyago/Tabular-data-generation#48]
Currently having issues while installing mac terminal with pip command. I have scikit learn 1.0 installed.

Collecting scikit-learn==0.23.2
  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [2515 lines of output]

**Comment by Diyago** [comment]
I suggest you create new env and then try to install this library. Reopen with still face the error

**Comment by abaccarini** [comment]
I am having this issue as well. Creating a fresh environment (I've tried both conda and venv) does not fix the problem. 

Can you please specify which versions of sklearn and tabgan are compatible together, as well as the version(s) of python?

**Comment by Diyago** [comment]
@anbaccar 
`!pip install tabgan==1.3.0 `

should work on colab
