### ISSUE TITLE
Mistake in Readme

### ISSUE THREAD

**Issue by ulhaqi12** [Diyago/Tabular-data-generation#63]
Hi,
I think I found a mistake in the readme file of this repository.
For the parameters being passed in function, the description of 'top_filter_quantile' should be "top quantile for postprocess filtering" instead of "bottom quantile for postprocess filtering".
![image](https://user-images.githubusercontent.com/44068298/225364196-016db0c3-9005-435b-ab85-ee84d770fee4.png)

It's not a big issue. I don't know the protocols of this repo. Should i change it and generate a PR or you will do it yourself?
Thanks.

Best Regards,
Ikram

**Comment by Diyago** [comment]
Hi! Thank you for pointing out! If you consider any further improvements -
you are welcome. You just need create PR to master branch. I will take a
look, rerun several test and might do next release, and even give you
credentials. The most desired think to add is diffusion models))

ср, 15 мар. 2023 г. в 18:48, Ikram Ul Haq ***@***.***>:

**Comment by ulhaqi12** [comment]
Hi @Diyago,
Sorry for being late to reply on this. Yes, I would love to contribute. I will explore research and different implementations of diffusion models for tabular data and can make a good module that can be integrated with this package.

Looking for your kind response

BR,
Ikram
