### ISSUE TITLE
Some issues araised when running Tab-GAN: 1) Manage Categorical Variables.    2) Batch size problem  

### ISSUE THREAD

**Issue by Morca97** [Diyago/Tabular-data-generation#66]
Hi, i am new to the Tab-GAN and i am trying to use it for my thesis, in order to manage class in some way class imbalance inside my dataset. 
However, i have faced some problems while using it:

1) In my example i have a tabular data containing both Numerical and Categorical examples, specifically the "Income_Category" column contains strigs:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/28482595/235954524-81ea8862-18a7-45e2-b6cf-369ab7b72804.png">

In the example shown on the TabGAN application the value of cat_cols is None, however in my case i should list the Categorical Columns (i.e cat_cols = ["Income_Category"].
However, when applying TabGAN is raise an error:  "Input X contains Nans"
<img width="820" alt="image" src="https://user-images.githubusercontent.com/28482595/235960308-b5c65a43-04a6-4a2e-83a4-def196325d7c.png">
Despite any Nans are present in the input DataFrame:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/28482595/235960651-6e2cf164-d43c-4c40-90e3-64b517d6cfe6.png">

Moreover, sometimes it make impossible for the GANGenerator to manage string values, in this case i should apply a categorical values encoding, what kind of preprocessing it is necessary to apply, one-hot or ordinal encoding, and how i should modify the param cat_cols?

2) Trying to modify the batch_size paramater of the GAN, raised this error:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/28482595/235962545-e238ec9b-0777-47e4-94de-678d3b878106.png">
What should be the cause?

**Comment by Diyago** [comment]
Hi! Thank you for raising the issue  could you provide some data sample to reproduce the problem

I will take a look

**Comment by Diyago** [comment]
And more think  could you label encode the category columns?

**Comment by Diyago** [comment]
I dont see in your screenshoot that you provided  cat_cols = ["Income_Category"]. Have you tried?

**Comment by Morca97** [comment]
Those are the file used, specifically for Training and Test sets:
[y_train.csv](https://github.com/Diyago/GAN-for-tabular-data/files/11389884/y_train.csv)
[X_train .csv](https://github.com/Diyago/GAN-for-tabular-data/files/11389885/X_train.csv)
[X_test .csv](https://github.com/Diyago/GAN-for-tabular-data/files/11389886/X_test.csv)

**Comment by Morca97** [comment]
Here the full screenshot, provided with cat_cols = ["Income_Category"]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/28482595/236014177-58fee9f5-3bfd-4c76-80ff-37acf67e7174.png">

**Comment by Morca97** [comment]
> And more think could you label encode the category columns?

I provide you also the Train and Test dataset with proper Ordinal Encoding of the "Income_Category" variable:
[X_train_label.csv](https://github.com/Diyago/GAN-for-tabular-data/files/11394894/X_train_label.csv)
[X_test_label.csv](https://github.com/Diyago/GAN-for-tabular-data/files/11394895/X_test_label.csv)
[y_train.csv](https://github.com/Diyago/GAN-for-tabular-data/files/11394896/y_train.csv)

**Comment by Diyago** [comment]
Fixed in new version for batch size, due to some several model limitations some batch sizes are not supported 

Try new version 
!pip install tabgan==1.3.2

**Comment by Diyago** [comment]
For Ordinal Encoding of the "Income_Category"  - everything works like a charm. Reopen with preproducing example maybe in colab
