### ISSUE TITLE
Reproducibility issue

### ISSUE THREAD

**Issue by Morca97** [Diyago/Tabular-data-generation#67]
**Describe the bug**
The Tab-GAN application does not retrieve same results when run multiple times with the same parameters' setting

**To Reproduce**

**Expected behavior**
When run different times with same parameters, the generated output must be the same. Instead, in this way it is not possible to understand if what we retrieve is good or just a lucky run. 
Random State is only present in the Adversarial Filtering, not in the GAN Synthetizer. 
There exist a way to retrieve always the same result when parameters are not changed?

**Comment by Diyago** [comment]
Fixed in new version, raise another if you still face problem

!pip install tabgan==1.3.2
