### ISSUE TITLE
IntCastingNaNError Despite No NaN values 

### ISSUE THREAD

**Issue by GenomicGandalf** [Diyago/Tabular-data-generation#69]
I made sure to filter out for NaN values with several different methods such as 

def isNaN(num):
    return num != num

Yet despite all methods assuring me there are no NaN values, I throw the "IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer" error on line 182 of astype.py 

My code is as follows in colab and I attached the dataset 

# Import 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

# Upload
df = pd.read_excel(io.BytesIO(uploaded['Nan_Error_Data.xlsx']))

COLS_USED = ['v', 'vw', 'o', 'c', 'h', 'l', 'n']
COLS_TRAIN = ['v', 'vw', 'o', 'h', 'l', 'n']

df = df[COLS_USED]

# Split into training and test sets
df_x_train, df_x_test, df_y_train, df_y_test = train_test_split(
    df.drop("c", axis=1),
    df["c"],
    test_size=0.20,
    #shuffle=False,
    random_state=42,
)

# Create dataframe versions for tabular GAN
df_x_test, df_y_test = df_x_test.reset_index(drop=True), \
  df_y_test.reset_index(drop=True)
df_y_train = pd.DataFrame(df_y_train)
df_y_test = pd.DataFrame(df_y_test)

# Pandas to Numpy
x_train = df_x_train.values
x_test = df_x_test.values
y_train = df_y_train.values
y_test = df_y_test.values

# Import 
from tabgan.sampler import GANGenerator
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Parameters
gen_x, gen_y = GANGenerator(gen_x_times=1.1, cat_cols=None,
           bot_filter_quantile=0.001, top_filter_quantile=0.999, \
              is_post_process=True,
           adversarial_model_params={
               "metrics": "rmse", "max_depth": 2, "max_bin": 100, 
               "learning_rate": 0.02, "random_state": \
                42, "n_estimators": 500,
           }, pregeneration_frac=2, only_generated_data=False,\
           gan_params = {"batch_size": 500, "patience": 25, \
          "epochs" : 500,}).generate_data_pipe(df_x_train, df_y_train,\
          df_x_test, deep_copy=True, only_adversarial=False, \
          use_adversarial=True)

[Nan_Error_Data.xlsx](https://github.com/Diyago/GAN-for-tabular-data/files/11538743/Nan_Error_Data.xlsx)

**Comment by Diyago** [comment]
The problem is with indexes in target you should make like in train or drop it

new_train3, new_target3 = GANGenerator(gen_x_times=1.1, cat_cols=None,
                                       bot_filter_quantile=0.001, top_filter_quantile=0.999, is_post_process=True,
                                       adversarial_model_params={
                                           "metrics": "AUC", "max_depth": 2, "max_bin": 100,
                                           "learning_rate": 0.02, "random_state": 42, "n_estimators": 500,
                                       }, pregeneration_frac=2, only_generated_data=False,
                                       gan_params={"batch_size": 500, "patience": 25,
                                                   "epochs": 500, }).generate_data_pipe(**train.reset_index(drop=True)**, target,
                                                                                        test, deep_copy=True,
                                                                                        only_adversarial=False,
                                                                                        use_adversarial=True)

**Comment by Diyago** [comment]
or pass target as None: 
target = None

**Comment by Diyago** [comment]
![image](https://github.com/Diyago/GAN-for-tabular-data/assets/8073766/80254204-cb1e-45ff-9350-0799160a8586)
