### ISSUE TITLE
LGBMClassifier.fit() got an unexpected keyword argument 'early_stopping_rounds'

### ISSUE THREAD

**Issue by eskayML** [Diyago/Tabular-data-generation#70]
Hello, i keep on getting this particular error from running the GANGenerator
is there a stable version i can install to avoid this.
![image](https://github.com/Diyago/GAN-for-tabular-data/assets/71832907/3eb1c8d9-1bb1-437b-928f-a73f0e32257f)

**Comment by catosaurusrex2003** [comment]
i am having same issue.
only @savioratharv can solve this.
all praise to mr. Patawar.
the lord of the worlds

**Comment by korebhaumik** [comment]
i am having same issue.
only @savioratharv can solve this.
all praise to mr. Patawar.
the lord of the worlds

**Comment by skancharapu775** [comment]
I am also having this issue. In a chegg forum where an anonymous user asked the same question, this answer was provided:

To fix the error message you are encountering, you need to update the LightGBM library version used in the code. The 'early_stopping_rounds' parameter was introduced in a later version of LightGBM, which is not compatible with the version currently installed.

There is more info on the answerer given here in the discussion post: https://github.com/Diyago/GAN-for-tabular-data/discussions/72
