### ISSUE TITLE
TypeError w/ Boolean Data

### ISSUE THREAD

**Issue by AnnetteBalaschak** [Diyago/Tabular-data-generation#78]
I have a dataset with boolean columns that refer to the bits in an IP address, at some point in training the CTGAN model the execution halts with the following error from NumPy:

"TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead."

![image](https://github.com/Diyago/GAN-for-tabular-data/assets/10779691/9332551d-2529-4f37-b794-f54f37a2e33e)

**Comment by Diyago** [comment]
hi! thank you for reaching out. Could you please give reproducible error with sample data
