### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ntheologos** [Diyago/Tabular-data-generation#80]
Followed installation instructions and once I run `python3 Research/run_experiment.py` I am getting the following error:

Traceback (most recent call last):
  File "./Research/run_experiment.py", line 10, in <module>
    from utils import save_exp_to_file, extend_gan_train, extend_from_original
  File "/Tabular-data-generation/Research/utils.py", line 8, in <module>
    from ctgan import _CTGANSynthesizer
ImportError: cannot import name '_CTGANSynthesizer' from 'ctgan' (/Tabular-data-generation/Research/ctgan/__init__.py)

**Comment by Yashasvee-second** [comment]
Hey, I  got the same error !

**Comment by Diyago** [comment]
I'm afraid it deprecated, updated readme.md. Thank you for noticing!
