### ISSUE TITLE
Hi! I tried to install the package. But I got the following error.

### ISSUE THREAD

**Issue by ValentinLo62** [Diyago/Tabular-data-generation#81]
I tried to install the package. But I got the following error.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[11], line 4
      2 import pandas as pd
      3 import numpy as np
----> 4 from tabgan.sampler import OriginalGenerator, GANGenerator, ForestDiffusionGenerator, LLMGenerator

File ~\AppData\Local\anaconda3\Lib\site-packages\tabgan\__init__.py:3
      1 # -*- coding: utf-8 -*-
      2 from pkg_resources import DistributionNotFound, get_distribution
----> 3 from .sampler import OriginalGenerator, Sampler, GANGenerator, ForestDiffusionGenerator, LLMGenerator
      5 try:
      6     # Change here if project is renamed and does not equal the package name
      7     dist_name = __name__

File ~\AppData\Local\anaconda3\Lib\site-packages\tabgan\sampler.py:10
      8 import pandas as pd
      9 import torch
---> 10 from be_great import GReaT
     12 from _ForestDiffusion import ForestDiffusionModel
     13 from _ctgan.synthesizer import _CTGANSynthesizer as CTGAN

ModuleNotFoundError: No module named 'be_great'

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu]

**Additional context**

**Comment by Diyago** [comment]
Hi! Is it locally tried installation or via colab?

**Comment by Diyago** [comment]
Could you please send output of pip list command?

**Comment by ValentinLo62** [comment]
At first 
it was a download to a local computer. But 
the same error is in colab.
-- 
Будем рады сотрудничеству с 
Вами!"Агентство Деловых Связей" ООО+375-29/116-49-23 моб.www.adc.pr.byДобрый день!Втр, 01 Окт 2024 03:26:44 -0700, Insaf 
Ashrapov ***@***.***> писал(а):> Hi! Is it locally tried installation or via colab?> > -- > Reply 
to this email directly or view it on GitHub:> https://github.com/Diyago/Tabular-data-generation/issues/81#issuecomment-2385410765> You 
are receiving this because you authored the thread.> > Message ID: >***@***.***>

**Comment by ValentinLo62** [comment]
It waspip install tabganRequirement already satisfied: tabgan in c:\users\lopan\appdata\local\anaconda3\lib\site-packages 
(2.2.1) 
Requirement already satisfied: pandas in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(2.2.2) 
Requirement already satisfied: numpy in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(1.26.4) 
Requirement already satisfied: category-encoders in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(2.6.3) 
Requirement already satisfied: torch>=1.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(2.4.1) 
Requirement already satisfied: lightgbm>=2.2.3 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(4.5.0) 
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(1.4.2) 
Requirement already satisfied: torchvision in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(0.19.1) 
Requirement already satisfied: python-dateutil in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(2.9.0.post0) 
Requirement already satisfied: tqdm in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(4.66.4) 
Requirement already satisfied: catboost in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(1.2.7) 
Requirement already satisfied: xgboost in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tabgan) 
(2.1.1) 
Requirement already satisfied: scipy in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from lightgbm>=2.2.3->tabgan) 
(1.13.1) 
Requirement already satisfied: joblib>=1.2.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->tabgan) 
(1.4.2) 
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from 
scikit-learn>=1.0.2->tabgan) (2.2.0) 
Requirement already satisfied: filelock in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torch>=1.0->tabgan) 
(3.13.1) 
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torch>=1.0->tabgan) 
(4.11.0) 
Requirement already satisfied: sympy in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torch>=1.0->tabgan) 
(1.12) 
Requirement already satisfied: networkx in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torch>=1.0->tabgan) 
(3.2.1) 
Requirement already satisfied: jinja2 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torch>=1.0->tabgan) 
(3.1.4) 
Requirement already satisfied: fsspec in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torch>=1.0->tabgan) 
(2024.3.1) 
Requirement already satisfied: setuptools in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torch>=1.0->tabgan) 
(69.5.1) 
Requirement already satisfied: graphviz in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from catboost->tabgan) 
(0.20.3) 
Requirement already satisfied: matplotlib in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from catboost->tabgan) 
(3.8.4) 
Requirement already satisfied: plotly in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from catboost->tabgan) 
(5.22.0) 
Requirement already satisfied: six in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from catboost->tabgan) 
(1.16.0) 
Requirement already satisfied: pytz>=2020.1 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from pandas->tabgan) 
(2024.1) 
Requirement already satisfied: tzdata>=2022.7 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from pandas->tabgan) 
(2023.3) 
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from category-encoders->tabgan) 
(0.14.2) 
Requirement already satisfied: patsy>=0.5.1 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from category-encoders->tabgan) 
(0.5.6) 
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from torchvision->tabgan) 
(10.3.0) 
Requirement already satisfied: colorama in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from tqdm->tabgan) 
(0.4.6) 
Requirement already satisfied: packaging>=21.3 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from 
statsmodels>=0.9.0->category-encoders->tabgan) (23.2) 
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from 
jinja2->torch>=1.0->tabgan) (2.1.3) 
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from 
matplotlib->catboost->tabgan) (1.2.0) 
Requirement already satisfied: cycler>=0.10 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from matplotlib->catboost->tabgan) 
(0.11.0) 
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from 
matplotlib->catboost->tabgan) (4.51.0) 
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from 
matplotlib->catboost->tabgan) (1.4.4) 
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from 
matplotlib->catboost->tabgan) (3.0.9) 
Requirement already satisfied: tenacity>=6.2.0 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from plotly->catboost->tabgan) 
(8.2.2) 
Requirement already satisfied: mpmath>=0.19 in c:\users\lopan\appdata\local\anaconda3\lib\site-packages (from sympy->torch>=1.0->tabgan) 
(1.3.0) 
Note: you may need to restart the kernel to use updated packages.import pandas as pd 
import numpy as np 
from tabgan.sampler import OriginalGenerator, GANGenerator--------------------------------------------------------------------------- 
ModuleNotFoundError                       
Traceback (most recent call last) 
Cell In[38], line 
4 
      2 import pandas as pd 
      3 import numpy as np 
----> 4 from tabgan.sampler import 
OriginalGenerator, GANGenerator 
 
File ~\AppData\Local\anaconda3\Lib\site-packages\tabgan\__init__.py:3 
      1 # -*- coding: utf-8 
-*- 
      2 from pkg_resources import DistributionNotFound, get_distribution 
----> 3 from .sampler import OriginalGenerator, Sampler, GANGenerator, ForestDiffusionGenerator, LLMGenerator 
      5 try: 
      6     # Change here if project is 
renamed and does not equal the package name 
      7     dist_name = __name__ 
 
File ~\AppData\Local\anaconda3\Lib\site-packages\tabgan\sampler.py:10 
      8 import pandas as pd 
      9 import torch 
---> 10 from be_great import 
GReaT 
     12 from _ForestDiffusion import ForestDiffusionModel 
     13 from _ctgan.synthesizer import _CTGANSynthesizer as CTGAN 
 
ModuleNotFoundError: No module named 
'be_great'-- Будем рады сотрудничеству с Вами!"Агентство Деловых Связей" ООО+375-29/116-49-23 моб.www.adc.pr.byДобрый 
день!Втр, 01 Окт 2024 03:28:28 -0700, Insaf Ashrapov ***@***.***> писал(а):> Could you please send output of 
pip list command?> > -- > Reply to this email directly or view it on GitHub:> 
https://github.com/Diyago/Tabular-data-generation/issues/81#issuecomment-2385414061> You are receiving this because you authored the 
thread.> > Message ID: >***@***.***>

**Comment by Diyago** [comment]
new version will be released 

workaround !pip install be-great

**Comment by Diyago** [comment]
https://pypi.org/project/tabgan/2.2.2/ 

pip install tabgan==2.2.2
