### ISSUE TITLE
TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

### ISSUE THREAD

**Issue by sweta30** [Diyago/Tabular-data-generation#82]
**Describe the bug**
While using tabgan with env having sklearn version greater than 1.4,` its raising below error: TypeError: OneHotEncoder.init() got an unexpected keyword argument 'sparse'.`

**To Reproduce**
- install latest scikit learn version and tabgan
- run any usecase with categorical columns

**Expected behavior**
- it should run

**Screenshots**
![image](https://github.com/user-attachments/assets/20eafc47-5512-47ee-ae2e-14462a62fb7a)

**Desktop (please complete the following information):**
 - Windows

**Additional context**
feature got deprecated in scikit learn and update is needed for tabgan.

**Comment by Diyago** [comment]
tried example from below - no errors. Please share problem via giving access to colab

``` python
from tabgan.sampler import OriginalGenerator, GANGenerator, ForestDiffusionGenerator, LLMGenerator
import pandas as pd
import numpy as np


train = pd.DataFrame(np.random.randint(-10, 150, size=(150, 4)), columns=list("ABCD"))
target = pd.DataFrame(np.random.randint(0, 2, size=(150, 1)), columns=list("Y"))
test = pd.DataFrame(np.random.randint(0, 100, size=(100, 4)), columns=list("ABCD"))

new_train1, new_target1 = OriginalGenerator().generate_data_pipe(train, target, test, )
new_train2, new_target2 = GANGenerator(gen_params={"batch_size": 500, "epochs": 10, "patience": 5 }).generate_data_pipe(train, target, test, )
new_train3, new_target3 = ForestDiffusionGenerator().generate_data_pipe(train, target, test, )
new_train4, new_target4 = LLMGenerator(gen_params={"batch_size": 32, 
                                                          "epochs": 4, "llm": "distilgpt2", "max_length": 500}).generate_data_pipe(train, target, test, )

new_train4, new_target4 = GANGenerator(gen_x_times=1.1, cat_cols=None,
           bot_filter_quantile=0.001, top_filter_quantile=0.999, is_post_process=True,
           adversarial_model_params={
               "metrics": "AUC", "max_depth": 2, "max_bin": 100, 
               "learning_rate": 0.02, "random_state": 42, "n_estimators": 100,
           }, pregeneration_frac=2, only_generated_data=False,
           gen_params = {"batch_size": 500, "patience": 25, "epochs" : 500,}).generate_data_pipe(train, target,
                                          test, deep_copy=True, only_adversarial=False, use_adversarial=True)
```

**Comment by Diyago** [comment]
https://stackoverflow.com/questions/63189787/typeerror-init-got-an-unexpected-keyword-argument-sparse maybe smth could help 


I believe it related with category_encoders library I use, but Im not sure:


one of the answers 
```
Resolved for me by deleting the following code:

from category_encoders import *

I guess this is probably because the One-hot-encoder in category_encoders module has override the One-hot-encoder in sklearn.preprocessing.
```

**Comment by Diyago** [comment]
reopen with new information

**Comment by sweta30** [comment]
Hi Sir,

Sorry for the late reply.
Please find colab notebook link to reproduce issue:
https://colab.research.google.com/drive/1A8Gq7Ou1AY-AJHDKvglXXbgr1NYJa50g?usp=sharing

This is coming from ctgan code which is part of tabgan. 'sparse' is already
deprecated in latest version of sklearn. Same we need to incorporate in
tabgan under ctgan code.

I have raised new issue:
https://github.com/Diyago/Tabular-data-generation/issues/83

Kindly let me know if this changes can be done in upcoming version of
tabgan release.

Thanks,
Sweta shaw.

**Comment by sweta30** [comment]
Sweta Kumari Shaw ***@***.***>
[image: Attachments]01:05 (1 minute ago)
to *Diyago/Tabular-data-generation*, Diyago/Tabular-data-generation, Author
Hi Sir,

Sorry for the late reply.
Please find colab notebook link to reproduce issue:
https://colab.research.google.com/drive/1A8Gq7Ou1AY-AJHDKvglXXbgr1NYJa50g?usp=sharing

This is coming from ctgan code which is part of tabgan. 'sparse' is already
deprecated in latest version of sklearn. Same we need to incorporate in
tabgan under ctgan code:
https://github.com/Diyago/Tabular-data-generation/blob/8865e5d5be5dc035cea340f4faa8d69014d44412/src/_ctgan/transformer.py#L50

I have raised new issue:
https://github.com/Diyago/Tabular-data-generation/issues/83

Kindly let me know if this changes can be done in upcoming version of
tabgan release.

Thanks,
Sweta shaw.
