### ISSUE TITLE
TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

### ISSUE THREAD

**Issue by sweta30** [Diyago/Tabular-data-generation#83]
**Describe the bug**
While using tabgan with env having sklearn version greater than 1.4,` its raising below error: TypeError: OneHotEncoder.init() got an unexpected keyword argument 'sparse'.`

**To Reproduce**
- install latest scikit learn version and tabgan
- run any usecase which can contain categorical columns
- Attached notebook for example.
- Initial investigation has been done by me. Its happening because of one deprecated argument 'sparse'
 is present in code . refer below link for same:
https://github.com/Diyago/Tabular-data-generation/blob/8865e5d5be5dc035cea340f4faa8d69014d44412/src/_ctgan/transformer.py#L50

colab notebook link : https://colab.research.google.com/drive/1A8Gq7Ou1AY-AJHDKvglXXbgr1NYJa50g?usp=sharing

**Expected behavior**
- it should run

**Screenshots**
![image](https://github.com/user-attachments/assets/20eafc47-5512-47ee-ae2e-14462a62fb7a)

**Desktop (please complete the following information):**
 - Windows

**Additional context**
feature got deprecated in scikit learn and update is needed for tabgan.

**Comment by sweta30** [comment]
OneHotEncoder docmentation: 
![image](https://github.com/user-attachments/assets/cf104a7b-f6ab-4f7d-b199-a24840eadcb7)

**Comment by sweta30** [comment]
Code which needs to be handled in tabgan to handle this deprecation : 
![image](https://github.com/user-attachments/assets/55f40bbe-b757-4a22-bf73-6b55cc0daac8)

**Comment by Diyago** [comment]
https://pypi.org/project/tabgan/2.2.3/ fixed!!!!

**Comment by sweta30** [comment]
Thanks a lot :)
